import type { Component } from 'vue'

export type MappingStatus = 'ready' | 'todo' | 'missing'

export interface ComponentMapping {
  slug: string
  primevue: string
  vuetify: string | null
  status: MappingStatus
  load: () => Promise<{ default: Component }>
}

export const componentMappings: ComponentMapping[] = [
  {
    slug: 'autocomplete',
    primevue: 'AutoComplete',
    vuetify: 'VAutocomplete',
    status: 'ready',
    load: () => import('@/comparisons/AutoComplete.vue'),
  },
  {
    slug: 'cascadeselect',
    primevue: 'CascadeSelect',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/CascadeSelect.vue'),
  },
  {
    slug: 'checkbox',
    primevue: 'Checkbox',
    vuetify: 'VCheckbox',
    status: 'ready',
    load: () => import('@/comparisons/Checkbox.vue'),
  },
  {
    slug: 'colorpicker',
    primevue: 'ColorPicker',
    vuetify: 'VColorPicker',
    status: 'ready',
    load: () => import('@/comparisons/ColorPicker.vue'),
  },
  {
    slug: 'datepicker',
    primevue: 'DatePicker',
    vuetify: 'VDateInput',
    status: 'ready',
    load: () => import('@/comparisons/DatePicker.vue'),
  },
  {
    slug: 'editor',
    primevue: 'Editor',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Editor.vue'),
  },
  {
    slug: 'floatlabel',
    primevue: 'FloatLabel',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/FloatLabel.vue'),
  },
  {
    slug: 'iconfield',
    primevue: 'IconField',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/IconField.vue'),
  },
  {
    slug: 'iftalabel',
    primevue: 'IftaLabel',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/IftaLabel.vue'),
  },
  {
    slug: 'inputgroup',
    primevue: 'InputGroup',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/InputGroup.vue'),
  },
  {
    slug: 'inputmask',
    primevue: 'InputMask',
    vuetify: 'VMaskInput',
    status: 'ready',
    load: () => import('@/comparisons/InputMask.vue'),
  },
  {
    slug: 'inputnumber',
    primevue: 'InputNumber',
    vuetify: 'VNumberInput',
    status: 'ready',
    load: () => import('@/comparisons/InputNumber.vue'),
  },
  {
    slug: 'inputotp',
    primevue: 'InputOtp',
    vuetify: 'VOtpInput',
    status: 'ready',
    load: () => import('@/comparisons/InputOtp.vue'),
  },
  {
    slug: 'inputtext',
    primevue: 'InputText',
    vuetify: 'VTextField',
    status: 'ready',
    load: () => import('@/comparisons/InputText.vue'),
  },
  {
    slug: 'knob',
    primevue: 'Knob',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Knob.vue'),
  },
  {
    slug: 'listbox',
    primevue: 'Listbox',
    vuetify: 'VList',
    status: 'ready',
    load: () => import('@/comparisons/Listbox.vue'),
  },
  {
    slug: 'multiselect',
    primevue: 'MultiSelect',
    vuetify: 'VSelect',
    status: 'ready',
    load: () => import('@/comparisons/MultiSelect.vue'),
  },
  {
    slug: 'password',
    primevue: 'Password',
    vuetify: 'VTextField',
    status: 'ready',
    load: () => import('@/comparisons/Password.vue'),
  },
  {
    slug: 'radiobuttongroup',
    primevue: 'RadioButtonGroup',
    vuetify: 'VRadioGroup',
    status: 'ready',
    load: () => import('@/comparisons/RadioButtonGroup.vue'),
  },
  {
    slug: 'radiobutton',
    primevue: 'RadioButton',
    vuetify: 'VRadio',
    status: 'ready',
    load: () => import('@/comparisons/RadioButton.vue'),
  },
  {
    slug: 'rating',
    primevue: 'Rating',
    vuetify: 'VRating',
    status: 'ready',
    load: () => import('@/comparisons/Rating.vue'),
  },
  {
    slug: 'select',
    primevue: 'Select',
    vuetify: 'VSelect',
    status: 'ready',
    load: () => import('@/comparisons/Select.vue'),
  },
  {
    slug: 'selectbutton',
    primevue: 'SelectButton',
    vuetify: 'VBtnToggle',
    status: 'ready',
    load: () => import('@/comparisons/SelectButton.vue'),
  },
  {
    slug: 'slider',
    primevue: 'Slider',
    vuetify: 'VSlider',
    status: 'ready',
    load: () => import('@/comparisons/Slider.vue'),
  },
  {
    slug: 'textarea',
    primevue: 'Textarea',
    vuetify: 'VTextarea',
    status: 'ready',
    load: () => import('@/comparisons/Textarea.vue'),
  },
  {
    slug: 'togglebutton',
    primevue: 'ToggleButton',
    vuetify: 'VBtn',
    status: 'ready',
    load: () => import('@/comparisons/ToggleButton.vue'),
  },
  {
    slug: 'toggleswitch',
    primevue: 'ToggleSwitch',
    vuetify: 'VSwitch',
    status: 'ready',
    load: () => import('@/comparisons/ToggleSwitch.vue'),
  },
  {
    slug: 'treeselect',
    primevue: 'TreeSelect',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/TreeSelect.vue'),
  },
  {
    slug: 'button',
    primevue: 'Button',
    vuetify: 'VBtn',
    status: 'ready',
    load: () => import('@/comparisons/Button.vue'),
  },
  {
    slug: 'speeddial',
    primevue: 'SpeedDial',
    vuetify: 'VSpeedDial',
    status: 'ready',
    load: () => import('@/comparisons/SpeedDial.vue'),
  },
  {
    slug: 'splitbutton',
    primevue: 'SplitButton',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/SplitButton.vue'),
  },
  {
    slug: 'datatable',
    primevue: 'DataTable',
    vuetify: 'VDataTable',
    status: 'todo',
    load: () => import('@/comparisons/DataTable.vue'),
  },
  {
    slug: 'dataview',
    primevue: 'DataView',
    vuetify: 'VDataIterator',
    status: 'todo',
    load: () => import('@/comparisons/DataView.vue'),
  },
  {
    slug: 'orderlist',
    primevue: 'OrderList',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/OrderList.vue'),
  },
  {
    slug: 'organizationchart',
    primevue: 'OrganizationChart',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/OrganizationChart.vue'),
  },
  {
    slug: 'paginator',
    primevue: 'Paginator',
    vuetify: 'VPagination',
    status: 'ready',
    load: () => import('@/comparisons/Paginator.vue'),
  },
  {
    slug: 'picklist',
    primevue: 'PickList',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/PickList.vue'),
  },
  {
    slug: 'timeline',
    primevue: 'Timeline',
    vuetify: 'VTimeline',
    status: 'ready',
    load: () => import('@/comparisons/Timeline.vue'),
  },
  {
    slug: 'tree',
    primevue: 'Tree',
    vuetify: 'VTreeview',
    status: 'todo',
    load: () => import('@/comparisons/Tree.vue'),
  },
  {
    slug: 'treetable',
    primevue: 'TreeTable',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/TreeTable.vue'),
  },
  {
    slug: 'virtualscroller',
    primevue: 'VirtualScroller',
    vuetify: 'VVirtualScroll',
    status: 'ready',
    load: () => import('@/comparisons/VirtualScroller.vue'),
  },
  {
    slug: 'accordion',
    primevue: 'Accordion',
    vuetify: 'VExpansionPanels',
    status: 'ready',
    load: () => import('@/comparisons/Accordion.vue'),
  },
  {
    slug: 'accordionpanel',
    primevue: 'AccordionPanel',
    vuetify: 'VExpansionPanel',
    status: 'ready',
    load: () => import('@/comparisons/AccordionPanel.vue'),
  },
  {
    slug: 'accordionheader',
    primevue: 'AccordionHeader',
    vuetify: 'VExpansionPanelTitle',
    status: 'ready',
    load: () => import('@/comparisons/AccordionHeader.vue'),
  },
  {
    slug: 'accordioncontent',
    primevue: 'AccordionContent',
    vuetify: 'VExpansionPanelText',
    status: 'ready',
    load: () => import('@/comparisons/AccordionContent.vue'),
  },
  {
    slug: 'card',
    primevue: 'Card',
    vuetify: 'VCard',
    status: 'ready',
    load: () => import('@/comparisons/Card.vue'),
  },
  {
    slug: 'deferredcontent',
    primevue: 'DeferredContent',
    vuetify: 'VLazy',
    status: 'ready',
    load: () => import('@/comparisons/DeferredContent.vue'),
  },
  {
    slug: 'divider',
    primevue: 'Divider',
    vuetify: 'VDivider',
    status: 'ready',
    load: () => import('@/comparisons/Divider.vue'),
  },
  {
    slug: 'fieldset',
    primevue: 'Fieldset',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Fieldset.vue'),
  },
  {
    slug: 'panel',
    primevue: 'Panel',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Panel.vue'),
  },
  {
    slug: 'scrollpanel',
    primevue: 'ScrollPanel',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/ScrollPanel.vue'),
  },
  {
    slug: 'splitter',
    primevue: 'Splitter',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Splitter.vue'),
  },
  {
    slug: 'stepper',
    primevue: 'Stepper',
    vuetify: 'VStepper',
    status: 'ready',
    load: () => import('@/comparisons/Stepper.vue'),
  },
  {
    slug: 'steplist',
    primevue: 'StepList',
    vuetify: 'VStepperHeader',
    status: 'ready',
    load: () => import('@/comparisons/StepList.vue'),
  },
  {
    slug: 'step',
    primevue: 'Step',
    vuetify: 'VStepperItem',
    status: 'ready',
    load: () => import('@/comparisons/Step.vue'),
  },
  {
    slug: 'steppanels',
    primevue: 'StepPanels',
    vuetify: 'VStepperWindow',
    status: 'ready',
    load: () => import('@/comparisons/StepPanels.vue'),
  },
  {
    slug: 'steppanel',
    primevue: 'StepPanel',
    vuetify: 'VStepperWindowItem',
    status: 'ready',
    load: () => import('@/comparisons/StepPanel.vue'),
  },
  {
    slug: 'stepitem',
    primevue: 'StepItem',
    vuetify: 'VStepperVertical',
    status: 'ready',
    load: () => import('@/comparisons/StepItem.vue'),
  },
  {
    slug: 'tabs',
    primevue: 'Tabs',
    vuetify: 'VTabs',
    status: 'ready',
    load: () => import('@/comparisons/Tabs.vue'),
  },
  {
    slug: 'tablist',
    primevue: 'TabList',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/TabList.vue'),
  },
  {
    slug: 'tab',
    primevue: 'Tab',
    vuetify: 'VTab',
    status: 'ready',
    load: () => import('@/comparisons/Tab.vue'),
  },
  {
    slug: 'tabpanels',
    primevue: 'TabPanels',
    vuetify: 'VTabsWindow',
    status: 'ready',
    load: () => import('@/comparisons/TabPanels.vue'),
  },
  {
    slug: 'tabpanel',
    primevue: 'TabPanel',
    vuetify: 'VTabsWindowItem',
    status: 'ready',
    load: () => import('@/comparisons/TabPanel.vue'),
  },
  {
    slug: 'toolbar',
    primevue: 'Toolbar',
    vuetify: 'VToolbar',
    status: 'ready',
    load: () => import('@/comparisons/Toolbar.vue'),
  },
  {
    slug: 'confirmdialog',
    primevue: 'ConfirmDialog',
    vuetify: 'VConfirmEdit',
    status: 'ready',
    load: () => import('@/comparisons/ConfirmDialog.vue'),
  },
  {
    slug: 'confirmpopup',
    primevue: 'ConfirmPopup',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/ConfirmPopup.vue'),
  },
  {
    slug: 'dialog',
    primevue: 'Dialog',
    vuetify: 'VDialog',
    status: 'ready',
    load: () => import('@/comparisons/Dialog.vue'),
  },
  {
    slug: 'drawer',
    primevue: 'Drawer',
    vuetify: 'VNavigationDrawer',
    status: 'ready',
    load: () => import('@/comparisons/Drawer.vue'),
  },
  {
    slug: 'dynamicdialog',
    primevue: 'DynamicDialog',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/DynamicDialog.vue'),
  },
  {
    slug: 'popover',
    primevue: 'Popover',
    vuetify: 'VMenu',
    status: 'ready',
    load: () => import('@/comparisons/Popover.vue'),
  },
  {
    slug: 'fileupload',
    primevue: 'FileUpload',
    vuetify: 'VFileUpload',
    status: 'todo',
    load: () => import('@/comparisons/FileUpload.vue'),
  },
  {
    slug: 'breadcrumb',
    primevue: 'Breadcrumb',
    vuetify: 'VBreadcrumbs',
    status: 'ready',
    load: () => import('@/comparisons/Breadcrumb.vue'),
  },
  {
    slug: 'contextmenu',
    primevue: 'ContextMenu',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/ContextMenu.vue'),
  },
  {
    slug: 'dock',
    primevue: 'Dock',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Dock.vue'),
  },
  {
    slug: 'menu',
    primevue: 'Menu',
    vuetify: 'VMenu',
    status: 'todo',
    load: () => import('@/comparisons/Menu.vue'),
  },
  {
    slug: 'menubar',
    primevue: 'Menubar',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Menubar.vue'),
  },
  {
    slug: 'megamenu',
    primevue: 'MegaMenu',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/MegaMenu.vue'),
  },
  {
    slug: 'panelmenu',
    primevue: 'PanelMenu',
    vuetify: 'VList',
    status: 'todo',
    load: () => import('@/comparisons/PanelMenu.vue'),
  },
  {
    slug: 'tieredmenu',
    primevue: 'TieredMenu',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/TieredMenu.vue'),
  },
  {
    slug: 'chart',
    primevue: 'Chart',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Chart.vue'),
  },
  {
    slug: 'message',
    primevue: 'Message',
    vuetify: 'VAlert',
    status: 'ready',
    load: () => import('@/comparisons/Message.vue'),
  },
  {
    slug: 'toast',
    primevue: 'Toast',
    vuetify: 'VSnackbarQueue',
    status: 'ready',
    load: () => import('@/comparisons/Toast.vue'),
  },
  {
    slug: 'carousel',
    primevue: 'Carousel',
    vuetify: 'VCarousel',
    status: 'ready',
    load: () => import('@/comparisons/Carousel.vue'),
  },
  {
    slug: 'galleria',
    primevue: 'Galleria',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Galleria.vue'),
  },
  {
    slug: 'image',
    primevue: 'Image',
    vuetify: 'VImg',
    status: 'ready',
    load: () => import('@/comparisons/Image.vue'),
  },
  {
    slug: 'imagecompare',
    primevue: 'ImageCompare',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/ImageCompare.vue'),
  },
  {
    slug: 'avatar',
    primevue: 'Avatar',
    vuetify: 'VAvatar',
    status: 'ready',
    load: () => import('@/comparisons/Avatar.vue'),
  },
  {
    slug: 'badge',
    primevue: 'Badge',
    vuetify: 'VBadge',
    status: 'ready',
    load: () => import('@/comparisons/Badge.vue'),
  },
  {
    slug: 'blockui',
    primevue: 'BlockUI',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/BlockUI.vue'),
  },
  {
    slug: 'chip',
    primevue: 'Chip',
    vuetify: 'VChip',
    status: 'ready',
    load: () => import('@/comparisons/Chip.vue'),
  },
  {
    slug: 'fluid',
    primevue: 'Fluid',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Fluid.vue'),
  },
  {
    slug: 'inplace',
    primevue: 'Inplace',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Inplace.vue'),
  },
  {
    slug: 'metergroup',
    primevue: 'MeterGroup',
    vuetify: 'VProgressLinear',
    status: 'ready',
    load: () => import('@/comparisons/MeterGroup.vue'),
  },
  {
    slug: 'progressbar',
    primevue: 'ProgressBar',
    vuetify: 'VProgressLinear',
    status: 'ready',
    load: () => import('@/comparisons/ProgressBar.vue'),
  },
  {
    slug: 'progressspinner',
    primevue: 'ProgressSpinner',
    vuetify: 'VProgressCircular',
    status: 'ready',
    load: () => import('@/comparisons/ProgressSpinner.vue'),
  },
  {
    slug: 'scrolltop',
    primevue: 'ScrollTop',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/ScrollTop.vue'),
  },
  {
    slug: 'skeleton',
    primevue: 'Skeleton',
    vuetify: 'VSkeletonLoader',
    status: 'ready',
    load: () => import('@/comparisons/Skeleton.vue'),
  },
  {
    slug: 'tag',
    primevue: 'Tag',
    vuetify: 'VChip',
    status: 'ready',
    load: () => import('@/comparisons/Tag.vue'),
  },
  {
    slug: 'terminal',
    primevue: 'Terminal',
    vuetify: null,
    status: 'missing',
    load: () => import('@/comparisons/Terminal.vue'),
  },
]

export const statusCounts = {
  ready: componentMappings.filter(m => m.status === 'ready').length,
  todo: componentMappings.filter(m => m.status === 'todo').length,
  missing: componentMappings.filter(m => m.status === 'missing').length,
}

export function getMappingBySlug (slug: string) {
  return componentMappings.find(m => m.slug === slug)
}

export function getStatusColor (status: MappingStatus) {
  if (status === 'ready') {
    return 'success'
  }
  if (status === 'todo') {
    return 'warning'
  }
  return 'secondary'
}

export function getStatusLabel (status: MappingStatus) {
  if (status === 'ready') {
    return 'Ready'
  }
  if (status === 'todo') {
    return 'In progress'
  }
  return 'No equivalent'
}
